### ISSUE TITLE
Intermediate certificate without "cRLSign" key usage flag

### ISSUE THREAD

**Issue by abgoldberg** [PeculiarVentures/PKI.js#72] opened 2016-09-14 19:13 UTC
Thanks for a great library. This should be really useful in my work.

I think there may be an unnecessarily strict constraint that leads to this error for a test case of mine:

"Unable to build certificate chain - intermediate certificate must have "cRLSign" key usage flag"

In this case, the intermediate certificate is not used to sign CRLs so I think it is valid to not have this flag. It would be good if there was a way to turn off this requirement via a configuration option.

See, for example, this discussion from http://security.stackexchange.com/a/49251 (from a very smart crypto guy)

"Since a CA is supposed to issue certificate and CRL, it should have, on a general basis, the keyCertSign and cRLSign flags. These two flags are sufficient. **If the CA does not intend to sign its own CRL, then it may omit the cRLSign flag**; however, a CA without the keyCertSign flag makes little sense." (emphasis added)

**Comment by rmhrisk** [comment] 2016-09-14 19:57
We explicitly do not support Delegated CRL signing at this time. To do so would require more than the requested change. I am inclined to say we should not make this change unless we support it completely. 

For example having an ability to pass in a policy specifying a set of directly trusted VAs that produce CRLs or graphing out to find a delegated signer one level under the issuer with CRLsign.

There are a lot of weird (and legacy) things out there in PKI but I have not seen delegated CRL signers since the late 90s early 00's; if I recall this was an option the Entrust PKI supported at the time.

The question then becomes what is the impact for:
A) Not taking a hack (and becoming more permissive as you suggest)
B) Not adding proper support for this case.

As I said I am predisposed to A) but the answer to B) would be dependent on how common this is in practice.

Given the PKI in question is likely a DOD PKI the question becomes how many of these are there?

Also If we were to do this work we would want to do this in the ES6 version as the ES5 one is on the path to deprecation.

**Comment by abgoldberg** [comment] 2016-09-14 20:31
In our case, it's not delegated CRL; it's no CRL at all. We use OCSP instead. cRLSign should only be required when verifying a CRL.

**Comment by rmhrisk** [comment] 2016-09-14 20:53
I understand your request now, thanks for clarifying.

I'm a bit torn, you are right that RFC5280 does not require a CA to have a CRL. That said I see little value, as a OKIoperator taking this option away from the issuer. Some UAs will not support OCSP and therefor the issued certs will be un-revocable.

This is why in the CABFORUM we mandated CRLsign on CA certificatez: https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.4.0.pdf

For this reason I would advise you reissue your CA certs with this permission. 

With that said it is reasonable, I think (Yury please correct me if I am wrong here) to have PKIjs only enforce presence when doing CRL verification.

**Comment by YuryStrozhevsky** [comment] 2016-09-15 06:38
In fact I made the check because NIST has such restriction in their PKITS. I will check if we could this check limited to a specific cases.

**Comment by YuryStrozhevsky** [comment] 2016-09-15 09:28
I need to say that in [ES6 version of PKIjs](https://github.com/PeculiarVentures/pkijs-es6) the issue is already fixed. Since the ES5 version is almost at "end-of-life" period I will close the issue and suggest you to move to ES6 version of PKIjs.

**Closed by YuryStrozhevsky** 2016-09-15 09:28 UTC
