### ISSUE TITLE
Error on require("pkijs")

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#152] opened 2018-02-17 08:50 UTC
PKIjs v2.1.22

```
>node
> var p = require("pkijs")
ReferenceError: regeneratorRuntime is not defined
    at C:\github\pv\xmldsigjs\node_modules\pkijs\build\CertificateChainValidationEngine.js:164:47
    at C:\github\pv\xmldsigjs\node_modules\pkijs\build\CertificateChainValidationEngine.js:479:4
    at Object.<anonymous> (C:\github\pv\xmldsigjs\node_modules\pkijs\build\CertificateChainValidationEngine.js:2754:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

**Comment by YuryStrozhevsky** [comment] 2018-02-17 10:01
This is not a PKIjs problem - you need to use correct Babel polyfill.

**Comment by microshine** [comment] 2018-02-17 10:05
Can you show example?

I installed pkijs to my project and cannot use it.

```
C:\tmp>npm i pkijs
npm WARN saveError ENOENT: no such file or directory, open 'C:\tmp\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\tmp\package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ pkijs@2.1.22
updated 1 package in 1.559s

C:\tmp>node
> var pkijs = require("pkijs");
ReferenceError: regeneratorRuntime is not defined
    at C:\tmp\node_modules\pkijs\build\CertificateChainValidationEngine.js:164:47
    at C:\tmp\node_modules\pkijs\build\CertificateChainValidationEngine.js:479:4
    at Object.<anonymous> (C:\tmp\node_modules\pkijs\build\CertificateChainValidationEngine.js:2754:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:
```

**Comment by microshine** [comment] 2018-02-17 10:27
I see there is no problem to compile PKIjs. It works ok. I'm talking about compiled ES5 script. New version of PKIjs in NPM has `build` directory with compiled ES5 code and doesn't have `src` for building. So NPM module is not working

**Comment by YuryStrozhevsky** [comment] 2018-02-17 10:37
For ES5 code, as I said, you need to use "babel-polifill" (of "...polyfill") package. And latest PKIjs version does have "src" directory for building.

**Comment by microshine** [comment] 2018-02-17 10:39
`src` folder exists. I missed it. Sorry

**Comment by microshine** [comment] 2018-02-17 10:45
Can you add `babel-polyfill` to PKIjs for ES5 version?
Otherwise all projects which use PKIjs ES5 must add `babel-polyfill` to dependency and republish

**Comment by YuryStrozhevsky** [comment] 2018-02-17 10:50
No. PKIjs does not rely on ES5 code and does not need this package during installation. Only the "ES5 users" of PKIjs should add it if they need to use ES5 code from PKIjs. The package is not a PKIjs problem.

**Comment by rmhrisk** [comment] 2018-02-18 06:47
@YuryStrozhevsky I am confused.

It seems to me that if require("pkijs") worked before it should work still but that does not sound like it is the case?

It seems maybe we have another issue; it seems to me that since PKIjs is now a ES6 project I would expect another ES6 project to be able to use it without taking a dependency on babel. Basically, I think babel should only be required when transpilation has been done.

I am guilty of not having kept a close eye on things in this project for a while but it seems like /build has ES5 and no ES6 but package.json main points at build directory; if that is the wont the ES6 project be getting the ES5 index?

**Comment by rmhrisk** [comment] 2018-02-18 07:04
@YuryStrozhevsky attached is a project that includes a ES5 and a ES6 sample project that attempts to use the new PKIjs:

[test-1.0.0.tgz.txt](https://github.com/PeculiarVentures/PKI.js/files/1734494/test-1.0.0.tgz.txt)

If you : 
```
tar -xvr test-1.0.0.tgz
cd package
npm i
node es6.js
```

You will see:
```
ES6 Success
/Users/rmh/Downloads/package/node_modules/pkijs/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import { setEngine, getEngine, getCrypto, getRandomValues, getOIDByAlgorithm, getAlgorithmParameters, createCMSECDSASignature, stringPrep, createECDSASignatureFromCMS, getAlgorithmByOID, getHashAlgorithm, kdfWithCounter, kdf } from "./common";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rmh/Downloads/package/es6.js:11:15)
```

And if you try : 
```
tar -xvr test-1.0.0.tgz
cd package
npm i
node es5.js
```

You will see:
```
/Users/rmh/Downloads/package/node_modules/pkijs/build/CertificateChainValidationEngine.js:164
			var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(certificate, validationEngine) {
			                                           ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/rmh/Downloads/package/node_modules/pkijs/build/CertificateChainValidationEngine.js:164:47
    at /Users/rmh/Downloads/package/node_modules/pkijs/build/CertificateChainValidationEngine.js:479:4
    at Object.<anonymous> (/Users/rmh/Downloads/package/node_modules/pkijs/build/CertificateChainValidationEngine.js:2754:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

(I am using node v8.2.1)

It seems to me this is not a good outcome. Neither the node ES5 applications or ES6 applications can currently use the PKIjs package.

How can we fix this?

**Comment by YuryStrozhevsky** [comment] 2018-02-18 10:49
I can’t check all the code at the moment but again I should point that all PKIjs examples are working well and this is a fact. As for additional dependence I again can say that this is not a pkijs problem how others would use the lib. We should not install any additional packages only because we think they would be useful. Maybe we would also include Webpack as a dependency - most probably pkijs users would use lib using Webpack. Or reactjs libs - maybe also include them as a dependcy to pkijs? My position is that we need to have only those packages on which pkijs is dependent.

**Comment by YuryStrozhevsky** [comment] 2018-02-18 11:07
I didn’t check code but seems I know why you have “ import error “. Seems you forgot some basic things about pkijs. First is that in order to have es6 application using pkijs working you need to apply Rollup at the end. Second thing is that there is no way at the moment how we could use “import” under Node. So seems that is why you had “into trouble” here.

**Comment by rmhrisk** [comment] 2018-02-19 01:46
I is my understanding that a pure ES6 application should not require to use Rollup, Rollup should be a step one applies to minimize the total package as it implements tree shaking to determine what parts of the code is used and not and build a package with just what is needed.

It seems that one should be able to use the ES6 logic without that minifcation step.

I am entirely open to this being on my end, but it seems to me broken that:

1. A pure ES6 application is not able to just npm add PKIjs and have it work

2. A ES5 application needs to know that babel was used to build the ES5 variant of PKIjs and include it at this layer instead. I can see the desire to include babel once, vs at each layer which could create issues (solvable with namespaces?) but maybe this is why it is the way it is for ES5, that said this still feels broken.

Ryan

**Comment by YuryStrozhevsky** [comment] 2018-02-19 07:01
Ryan, as I said it is not possible to use "import" directly from any Node.js application. It is possible now to use "import" from Chrome, but in order to do this application must be slightly modified. So, in order to have reall ES6 application anyone need to make a big module without imports - all included files must be in one place. **No other way** how to write ES6 applications exists at the moment. User may use Rollup, or may just put all modules by hand - does not matter. All "import" directives must be illuminated. So, this code you wrote is a completely mistaken code:
```javascript
class Test {
    run () {
        console.log("ES6 Success");
    }
}

const t = new Test();
t.run()

const pkijs = require("pkijs/src");
```

There is no way how to use PKIjs via "require" in Node.js just because there is no way for Node.js how to use "import". But in the modern Node.js versions you could use real ES6 code (with "async/await" etc.) but the code **must be** combined in one file before usage in Node.js environment. The example is in PKIjs:
```
npm run build:tests
mocha test/nodePKCS12Example.js
```

You could check "test/nodePKCS12Example.js" - this is a real Node-native application having native ES6 code from PKIjs inside, with all these "async/await" in there. And no additional packages/polyfills required, btw.

As for your ES5 code: as I said there is a requirement for application to use "babel-polyfill" before PKIjs ES5 code. And you confirmed it is working well even for your test code. So, get back to your proposal to inlcude "babel-polyfill" directly into PKIjs ES5 code which we build. Here is what I found [in the official Babel README](https://github.com/babel/babel-preset-env/tree/2.0#usebuiltins-entry):

> NOTE: Only use require("babel-polyfill"); once in your whole app. Multiple imports or requires of babel-polyfill will throw an error since it can cause global collisions and other issues that are hard to trace. We recommend creating a single entry file that only contains the require statement

And at a little bottom [here](https://github.com/babel/babel-preset-env/tree/2.0#usebuiltins-false)

> Don't add polyfills automatically per file, or transform import "babel-polyfill" to individual polyfills

So, again I should say that best way how to solve the "issue" is to recommend end-user to change their applications. In other cases we could produce much more problem than solving them.

**Comment by YuryStrozhevsky** [comment] 2018-02-19 07:05
BTW, probably you missed it but latest Hancock code is already running using latest PKIjs version. And the project has ES6 code as a core and ES5 code at the end, as you also know.

**Comment by rmhrisk** [comment] 2018-02-19 08:04
Yury, thank you for the explanation. 

I think I understand now.


This is a useful article from last year on this topic:
https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c

It sounds like we don’t have a better option :(

**Comment by YuryStrozhevsky** [comment] 2018-02-19 09:44
The only thing I want to append here is the information that in latest PKIjs code I was using "async functions". Since we are using Babel application builder must consider using "babel-preset-env" (or "babel-preset-es2017" but it is deprecated for now) instead of "babel-preset-es2015".

**Comment by YuryStrozhevsky** [comment] 2018-03-03 11:04
Closed as seems as a conclusion all came to opinion there is no another choice here.

**Closed by YuryStrozhevsky** 2018-03-03 11:04 UTC
