### ISSUE TITLE
OpenSSL.js

### ISSUE THREAD

**Issue by TJKoury** [PeculiarVentures/PKI.js#252] opened 2019-11-07 05:16 UTC
[Here it is](https://github.com/DigitalArsenal/openssl.js#readme) 

After trying to add a few more algorithms to the cert gen code here, my company finally just posted all of OpenSSL to wasm using the new wasi interface standard.  Big thanks to wasmer.io for their work in streamlining the workflow.

**Comment by rmhrisk** [comment] 2019-11-07 05:22
Is there a bug or a ask here?

**Comment by TJKoury** [comment] 2019-11-07 05:25
Related to my pull #230, is it worth doing Or does an implementation like this negate the need?

**Comment by rmhrisk** [comment] 2019-11-07 05:27
I’m guessing your bug was intended as some sort of advertisement? 

I’m also guessing this is the PR you started for adding 256k1 but didn’t finish? https://github.com/PeculiarVentures/PKI.js/pull/230

From the text of that bug is seems no issues were raised; if there is something actionable for us we would love to hear it.

If not please close this bug.

If you don’t intend to address the minor feedback on that PR please just close it.

**Comment by TJKoury** [comment] 2019-11-07 05:30
This is not an advertisement, the code is Apache-2.0.  I’m looking for feedback to see if it’s worth finishing the pull, or if the community here has some reason why a direct port of OpenSSL is not a good idea.

**Comment by TJKoury** [comment] 2019-11-07 05:32
I am also looking to add ED25519, and other functionality.  Just trying to make sure I’m not wasting time.

**Comment by rmhrisk** [comment] 2019-11-07 05:33
No, wasm based crypto implementations will have issues like timing attacks and other issues that will make it not suitable for production implementations.

This is why we’re based on webcrypto, where no native implementation is available (such as in the case of 256k1) it may be appropriate two use a wasm implementation of an algorithm but otherwise we would advice against it.

Having 256k1 support on PKIjs is desirable so we would take the PR if it meets basic quality criteria as is discussed in the bug so if you finish it we would still accept it.

If you do not intend to finish it for you we don’t have the time to do so so it’s best to close it.

**Comment by rmhrisk** [comment] 2019-11-07 05:35
I also want to see Ed25519 in PKIJs and our webcrypto polyfills so quality PRs there would also be considered.

**Comment by TJKoury** [comment] 2019-11-07 05:35
I’ll finish it

**Comment by TJKoury** [comment] 2019-11-07 05:36
The timing issues are negated by using Crypto.getRandomValues in the browser version.

**Comment by rmhrisk** [comment] 2019-11-07 05:45
Unless your an cryptographer or someone on the team who created the wasm port and that person has done the analysis and associated fixes against the wasm  port it’s highly likely it has issues.

The associated risks may be acceptable in some use cases, and not in others. 

It is true that quality random numbers are one of the many important issues that are hard in cryptography and especially hard in JavaScript environments.

Using quality random numbers does not however prevent all issues and compilers, especially cross compilers, are weird machines and you just don’t get something good because you started with something good.

Anyway, we strongly advise against using JavaScript crypto, WASM, especially WASM generates and not evaluated, is not something we recommend unless alternatives do not exist and the risk is acceptable.

**Comment by TJKoury** [comment] 2019-11-07 06:04
We did create the wasm port, you can see our script in packages/openssl/build.sh.

I agree that crypto in JavaScript is problematic, but directly porting the heavily reviewed and used OpenSSL seems like the best option.

**Comment by YuryStrozhevsky** [comment] 2019-11-07 06:09
@TJKoury How did you test the new lib? I do not see any significant tests in the new lib. Have you made a "cross testing" when, for example, you make certificate using JS lib and then test signature using native OpenSSL?

**Comment by YuryStrozhevsky** [comment] 2019-11-07 06:17
@TJKoury Also came in mind - how you would cover situation with OpenSLL updates? You would rebuild your code always after that?

**Comment by TJKoury** [comment] 2019-11-07 10:58
@YuryStrozhevsky Working on a test suite now but yes, we tried deterministic commands and made sure the results worked in both versions.  You would have to build new versions but it doesn’t take long with that build script.

**Comment by YuryStrozhevsky** [comment] 2019-11-08 05:24
Do not see a reason to have it here, at least in open state.

**Closed by YuryStrozhevsky** 2019-11-08 05:24 UTC

**Comment by rmhrisk** [comment] 2019-11-08 17:43
> I agree that crypto in JavaScript is problematic, but directly porting the heavily reviewed and used OpenSSL seems like the best option.

While implementing an algorithm, implemented must consider how their operational environment and compiler; as just two examples; the reviews of OpenSSLs C don’t necessarily net a secure WASM implementation. It’s likely better than nothing, but without evaluation you just don’t know.
