### ISSUE TITLE
SignedData.verify() TypeError: Cannot use 'in' operator to search for 'code' in Incorrect public key algorithm: 1.2.840.113549.1.1.1

### ISSUE THREAD

**Issue by asnov** [PeculiarVentures/PKI.js#102] opened 2017-04-28 20:05 UTC
Hi,
I stucked with an issue in SignedData.verify method. Here is the code (https://github.com/asnov/pkijsIssue/blob/master/index.ts):
```typescript
const cmsSignedSimp: SignedData = new SignedData({
    certificates: [certificate],
    signerInfos: [
        new SignerInfo({
            version: certificate.version,
            sid: new IssuerAndSerialNumber({
                issuer: certificate.issuer,
                serialNumber: certificate.serialNumber
            }),
            digestAlgorithm: certificate.signatureAlgorithm,
            signature: new asn1js.OctetString({valueHex: signedBuffer}),
        })
    ],
});

cmsSignedSimp
    .verify({
        signer: 0,
        data: signedDataBuffer,
        extendedMode: true,
    })
    .then(verifyResult => {
        if (!verifyResult.signatureVerified) {
            delete verifyResult.signerCertificate;
            delete verifyResult.signerCertificateVerified;
            console.error(`SignedData.verify() failed`, verifyResult);
        } else {
            console.log(`SignedData.verify() succeed.`);
        }
    })
    .catch(err => {
        console.error(`SignedData.verify() catched error`, err);
    });
```
It gives me the next error:
`SignedData.verify() catched error TypeError: Cannot use 'in' operator to search for 'code' in Incorrect public key algorithm: 1.2.840.113549.1.1.1`

When I patch the pkijs/build/SignedData.js like this (https://github.com/asnov/pkijsIssue/blob/master/SignedData.patch):
```
742c742
< 				shaAlgorithm = signerInfoHashAlgorithm.name;
---
> 				shaAlgorithm = signerInfoHashAlgorithm.hash.name;
```
It works fine i.e. SignedData.verify() failed because of wrong signed data.
Could you check, please, whether it is a bug in PKI.js?

Thank you!

**Comment by YuryStrozhevsky** [comment] 2017-04-29 08:20
@asnov First of all it is hard to say where is the problem without any finished code and certificate data. Second: why not just use [existing example](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CMSSignedComplexExample/es6.js)? There you could find a correct way how to initialize SignedData content.

**Comment by asnov** [comment] 2017-04-29 12:37
@YuryStrozhevsky I was prepared :)
First: especially for this issue I created a demo project with finished code and certificate data. I posted two links to files from it above. Here is a link for a project itself: https://github.com/asnov/pkijsIssue
You could use this command to run it and to see the error:
`git clone https://github.com/asnov/pkijsIssue.git && cd pkijsIssue && npm install && npm start`
Second: I used example code to initialize SignedData content but I created tiny separate project because it is twelve times smaller and I believe easy to troubleshoot.

**Comment by YuryStrozhevsky** [comment] 2017-04-29 12:40
@asnov The error you have could be because of incorrect certificate. Do you have an example certificate?

**Comment by YuryStrozhevsky** [comment] 2017-04-29 12:45
@asnov You think signature should looks like this? :)
```javascript
const signedBuffer: ArrayBuffer = stringToArrayBuffer(fromBase64('base64 signature'));
...
const cmsSignedSimp: SignedData = new SignedData({
    certificates: [certificate],
    signerInfos: [
        new SignerInfo({
            version: certificate.version,
            sid: new IssuerAndSerialNumber({
                issuer: certificate.issuer,
                serialNumber: certificate.serialNumber
            }),
            digestAlgorithm: certificate.signatureAlgorithm,
            signature: new asn1js.OctetString({valueHex: signedBuffer}),
        })
    ],
});
```

**Comment by YuryStrozhevsky** [comment] 2017-04-29 12:47
@asnov So, I do recommend you to use existing PKI.js example, put your certificate there and the try to run - most probably you would not have any errors.

**Comment by asnov** [comment] 2017-04-29 12:48
I used this certificate in the demo: https://certs.godaddy.com/repository/gdig2.crt but I tried with three others.

**Comment by asnov** [comment] 2017-04-29 12:50
@YuryStrozhevsky Yes, sure, I believe WRONG signature could look like this. And I expect to receive correct error but not **the code exception**.

**Comment by YuryStrozhevsky** [comment] 2017-04-29 12:51
@asnov So, your real problem is that when you are using PKI.js by the wrong way you got wrong results? :)

**Comment by asnov** [comment] 2017-04-29 13:22
@YuryStrozhevsky It looks like it is easier to fix the issue then to prove that it is exist ;))) 
I wouldn't say that this way is wrong because there are no many documentation for the library and it is difficult to say which way is right. JsDoc does not describe the parameters array. Examples does not cover all use-cases. Typescript typing helps but it can't replace the docs.
Ok, I will try ~~to mate hedgehog and snake~~ use your certificate and signature in my demo or change your example following my use-case.

**Comment by YuryStrozhevsky** [comment] 2017-05-23 16:49
Any news?

**Comment by YuryStrozhevsky** [comment] 2017-06-11 10:05
Closed as it seems to be "non-needed" any more.

**Comment by asnov** [comment] 2017-06-11 18:03
Not yet. Actually, I'm stucked.
I can't use [existing example](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CMSSignedComplexExample/es6.js) because I don't have the private key of my certificate. It is on the server. The server (Azure KeyVault) does signing using the digest value and JsonWebKeySignatureAlorigthm.RS256 as parameters. The result has completely different structure that ContentInfo and SignedData objects so I can't initialize SignedData content using schema, as you do in your example. When I initialize it with parameters like you do in other examples it works (at least I get SignedData object) but you said it is a wrong way.
So I think I need somebody's help to get out of this.

**Comment by rmhrisk** [comment] 2017-06-11 19:08
@asnov without a small reproducible example of your problem it's near impossible to help. I recommend making a git repo that contains the smallest possible sample to reproduce your problem and point us at that.

**Comment by asnov** [comment] 2017-06-11 19:53
@rmhrisk I made a git repo with finished code and certificate data. I posted two links to files from it above. Here is a link for a project itself: https://github.com/asnov/pkijsIssue
You could use this command to run it and to see the error:
`git clone https://github.com/asnov/pkijsIssue.git && cd pkijsIssue && npm install && npm start`

**Expected behavior:** You should see `SignedData.verify() failed` message
**Real behaviour:** You will see `SignedData.verify() catched error TypeError: Cannot use 'in' operator to search for 'code' in Incorrect public key algorithm: 1.2.840.113549.1.1.1` message. This means that JS exception happens in library.

**My patch:** if you will patch the library as I suggest:
`patch pkijs/build/SignedData.js SignedData.patch`
and run project again:
`npm start`
you will see the expected behaviour.

Because of this I conclude there is an algorithm mistake in the library code. I'm sorry but I can't explain this more clearly that I did because I'm quite new in cryptography. At the moment I use your library in the real project with this patch (as it doesn't work in the other way) and I hope you will include it to the code.
Thank you for your patience.

**Comment by YuryStrozhevsky** [comment] 2018-02-20 06:16
Do not think we could help here.

**Closed by YuryStrozhevsky** 2018-02-20 06:16 UTC
